server:
  port: 8081

spring:
  application:
    name: catalogue-service
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue_db
    username: catalogue_user
    password: catalogue_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    enabled: false